加速docker build
xiachufang/actions-feishu pull request #2
Opened 2021-05-19 08:48 UTC by StrayDragon

2021-05-19 10:56 UTC, StrayDragon commented on Dockerfile
> +ENTRYPOINT [ "bin/feishu" ]
```suggestion
#ENTRYPOINT [ "/app" ]
ENTRYPOINT [ "bin/feishu" ]
```

2021-05-19 10:58 UTC, StrayDragon commented on Dockerfile
> +#FROM golang:1.14.4-alpine3.12 as builder
```suggestion
#FROM golang:1.14.4-alpine3.12 as builder
FROM golang:1.14.4-alpine3.12
```

2021-05-19 11:16 UTC, x1ah requested changes

2021-05-19 11:16 UTC, x1ah commented on Dockerfile
> +#FROM scratch
这样会导致 build 出来的镜像大很多，`scratch` 也就几兆，`golang:1.14.4-alpine3.12` 至少几百兆。

2021-05-19 11:25 UTC, StrayDragon commented on Dockerfile
> +#FROM scratch
好, 我改下,  只顾着精简步骤了...
但这个build的时间还是太久了, 要1分钟左右, 
能把这玩意放在docker registry 或 github registry 让Github Actions走 pull 或 cache build吗?

2021-05-20 02:41 UTC, StrayDragon commented on Dockerfile
> +FROM golang:1.14.4-alpine3.12
```suggestion
FROM golang:1.14.4-alpine3.12 as builder
```

2021-05-20 03:36 UTC, StrayDragon commented on Dockerfile
> +#FROM scratch
https://steele.blue/tiny-github-actions/

找到一篇挺好的文章处理这个, 看上去符合需要 😉

2021-05-20 06:37 UTC, x1ah commented on Dockerfile
> +#    apk add --no-cache make curl git build-base
```suggestion
```

2021-05-20 06:37 UTC, x1ah approved these changes

2021-05-20 06:37 UTC, merged